### ISSUE TITLE
Rework Alpha 1 Milestone

### ISSUE THREAD

**Issue by Trojaner25** [RocketMod/Rocket#1017]
**Alpha 1:**
- [x] Rocket.API
    - [x] Chat
    - [x] Commands [Todo: add Container to CommandContext for transient dependencies]
    - [x] Configurations
    - [x] DI
    - [x] Eventing
    - [x] Handlers
    - [x] I18N
    - [x] Logging
    - [x] Permissions
    - [x] Players
        - [x] Player
        - [x] PlayerManager
    - [x] Plugins
    - [x] Scheduling
- [x] Rocket.Core
    - [x] Commands
        - [x] CommandContext 
        - [x] CommandHandler
    - [x] Configurations 
        - [x] JsonConfiguration
    - [x] DI
         - [x] Unity Ioc
         - [x] DependencyResolvers
    - [x] Eventing
    - [x] Events
        - [x] Players
        - [x] Plugins
    - [x] I18N
    - [x] Logging 
        - [x] Console Logger
    - [x] Permissions
        - [x] PermissionsProvider Implementation
        - [x] Working tests
    - [x] Plugins
- [x] Rocket.UnityEngine 
    - [x] Scheduling
        - [x] UnityTaskScheduler
- [x] Rocket.Unturned 
    - [x] ChatManager
    - [x] Commands
        - [x] Vanilla commands wrapper
    - [x] PlayerManager
    - [x] Unturned Console integration
    - [x] Events
        - [x] Implementation
        - [x] Players
            - [x] UnturnedPlayerChatEvent
            - [x] UnturnedPlayerDeathEvent
            - [x] UnturnedPlayerDeadEvent
            - [x] PlayerKickEvent
            - [x] PlayerBanEvent
            - [x] PlayerPreConnectEvent
            - [x] PlayerConnectEvent
            - [x] PlayerDisconnecEvent
