### ISSUE TITLE
Rework Alpha 2 Milestone 

### ISSUE THREAD

**Issue by Trojaner25** [RocketMod/Rocket#1018]
- [x] Rocket.API
    - [x] Commands
         - [x] ICommandParameters
         - [x] Child Commands
    - [x] Drop Handlers
    - [x] Economy
         - [x] EconomyProvider
    - [x] Logging
         - [x] Add ConsoleColors
    - [x] Permissions
         - [x] PermissionResult
         - [x] Refactor Permissions
- [x] Rocket.Core
    - [x] Commands
         - [x] CommandParameters
         - [x] Command Aliases         
         - [x] [[Built in Rocket commands]](https://github.com/RocketMod/Rocket/tree/master/Rocket.Core/Commands)
         - [x] Child Commands
         - [x] Command Attributes
    - [x] Configurations
        - [x] XmlConfiguration
    - [x] DI
        - [x] ProviderProxies 
             - [x] CommandHandlerProxy
             - [x] CommandProviderProxy
             - [x] PermissionsManagerProxy
             - [x] PluginManagerProxy
             - [x] LoggerProxy
    - [x] Formatters    
    - [x] Players
        - [x] PlayerTypeConverter
        - [x] OnlinePlayerTypeConverter
    - [x] Plugins
        - [x] Copy dll resources to plugin dir automatically
- [x] Rocket.Unturned
    - [x] Commands
         - [x] [[Built in Rocket.Unturned commands]](https://github.com/RocketMod/Rocket.Unturned/tree/master/Rocket.Unturned/Commands)
             - [x] Admin
             - [x] Broadcast
             - [x] Compass
             - [x] Effect
             - [x] Exit
             - [x] Heal
             - [x] Home
             - [x] I
             - [x] Investigate
             - [x] More
             - [x] Tp
             - [x] Tphere
             - [x] Unadmin
             - [x] V
    - [x] Events
        - [x] Unturned specific events
    - [x] UnturnedPlayer Formatting
    - [x] Update to latest Rocket.API
- [x] Misc:
    - [x] Ensure IsAlive is always checked everywhere before calling related code

**Comment by Trojaner25** [comment]
Code review as done
