### ISSUE TITLE
Rework Beta 1 Milestone

### ISSUE THREAD

**Issue by fr34kyn01535** [RocketMod/Rocket#1035]
- [x] Finish API documentation
- [x] File logger
- [x] Migrator plugin (migrate old configs and permissions etc from RM5, not to be confused with config migrations)
- [x] Plugins via NuGet
- [x] Port some plugins
- [ ] Unity Configurations
- [ ] Vanish for Rocket.Unturned
